apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
####################
#  Tasks           #
####################
- tasks/goodbye.yaml
- tasks/hello-world.yaml
- tasks/hi-emily.yaml
#####################
#  Pipelines        #
#####################
- pipelines/hello-goodbye.yaml

