apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye-pipeline
spec:
  tasks:
    - name: hello-world
      taskRef:
        name: hello
    - name: goodbye-world
      taskRef:
        name: goodbye
      runAfter:
        - hello-world
